//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LEGASY.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LegasyEntities : DbContext
    {
        public LegasyEntities()
            : base("name=LegasyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountTypes> AccountTypes { get; set; }
        public virtual DbSet<Banks> Banks { get; set; }
        public virtual DbSet<BanksAccount> BanksAccount { get; set; }
        public virtual DbSet<BudgetsConcept> BudgetsConcept { get; set; }
        public virtual DbSet<BudgetsYear> BudgetsYear { get; set; }
        public virtual DbSet<CasesAreas> CasesAreas { get; set; }
        public virtual DbSet<CasesCategory> CasesCategory { get; set; }
        public virtual DbSet<CasesClass> CasesClass { get; set; }
        public virtual DbSet<CasesDocuments> CasesDocuments { get; set; }
        public virtual DbSet<CasesInstances> CasesInstances { get; set; }
        public virtual DbSet<CasesParts> CasesParts { get; set; }
        public virtual DbSet<CasesPartsType> CasesPartsType { get; set; }
        public virtual DbSet<CasesPretensions> CasesPretensions { get; set; }
        public virtual DbSet<CasesProcedure> CasesProcedure { get; set; }
        public virtual DbSet<CasesProcesses> CasesProcesses { get; set; }
        public virtual DbSet<CasesSpendings> CasesSpendings { get; set; }
        public virtual DbSet<CasesTypes> CasesTypes { get; set; }
        public virtual DbSet<Cities> Cities { get; set; }
        public virtual DbSet<Companies> Companies { get; set; }
        public virtual DbSet<Countries> Countries { get; set; }
        public virtual DbSet<Currencies> Currencies { get; set; }
        public virtual DbSet<Partners> Partners { get; set; }
        public virtual DbSet<PartnersCivilStatus> PartnersCivilStatus { get; set; }
        public virtual DbSet<PartnersClass> PartnersClass { get; set; }
        public virtual DbSet<PartnersGender> PartnersGender { get; set; }
        public virtual DbSet<PartnersPerson> PartnersPerson { get; set; }
        public virtual DbSet<PartnersType> PartnersType { get; set; }
        public virtual DbSet<States> States { get; set; }
        public virtual DbSet<Subsidiaries> Subsidiaries { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UsersAuthorization> UsersAuthorization { get; set; }
        public virtual DbSet<UsersModules> UsersModules { get; set; }
        public virtual DbSet<UsersPermission> UsersPermission { get; set; }
        public virtual DbSet<UsersRole> UsersRole { get; set; }
        public virtual DbSet<Sesions> Sesions { get; set; }
    
        [DbFunction("LegasyEntities", "Seguridad_Fn_MostrarModulos")]
        public virtual IQueryable<Seguridad_Fn_MostrarModulos_Result> Seguridad_Fn_MostrarModulos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Seguridad_Fn_MostrarModulos_Result>("[LegasyEntities].[Seguridad_Fn_MostrarModulos]()");
        }
    
        [DbFunction("LegasyEntities", "Seguridad_Fn_MostrarPermisos")]
        public virtual IQueryable<Seguridad_Fn_MostrarPermisos_Result> Seguridad_Fn_MostrarPermisos(Nullable<int> idModulo)
        {
            var idModuloParameter = idModulo.HasValue ?
                new ObjectParameter("IdModulo", idModulo) :
                new ObjectParameter("IdModulo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Seguridad_Fn_MostrarPermisos_Result>("[LegasyEntities].[Seguridad_Fn_MostrarPermisos](@IdModulo)", idModuloParameter);
        }
    
        public virtual int Seguridad_P_GuardarModulo(Nullable<bool> codeStatus, string name, string shortName, string description, Nullable<long> userIdCreate, Nullable<System.DateTime> dateCrate, ObjectParameter mENSAJE, ObjectParameter rESPUESTA)
        {
            var codeStatusParameter = codeStatus.HasValue ?
                new ObjectParameter("CodeStatus", codeStatus) :
                new ObjectParameter("CodeStatus", typeof(bool));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var shortNameParameter = shortName != null ?
                new ObjectParameter("ShortName", shortName) :
                new ObjectParameter("ShortName", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var userIdCreateParameter = userIdCreate.HasValue ?
                new ObjectParameter("UserIdCreate", userIdCreate) :
                new ObjectParameter("UserIdCreate", typeof(long));
    
            var dateCrateParameter = dateCrate.HasValue ?
                new ObjectParameter("DateCrate", dateCrate) :
                new ObjectParameter("DateCrate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Seguridad_P_GuardarModulo", codeStatusParameter, nameParameter, shortNameParameter, descriptionParameter, userIdCreateParameter, dateCrateParameter, mENSAJE, rESPUESTA);
        }
    
        public virtual int Seguridad_P_GuardarPermiso(Nullable<long> entryCodeModule, Nullable<bool> entryCodeStatus, string entryName, string entryDescription, Nullable<long> userIDcreate, Nullable<System.DateTime> dateCreate, ObjectParameter mENSAJE, ObjectParameter rESPUESTA)
        {
            var entryCodeModuleParameter = entryCodeModule.HasValue ?
                new ObjectParameter("entryCodeModule", entryCodeModule) :
                new ObjectParameter("entryCodeModule", typeof(long));
    
            var entryCodeStatusParameter = entryCodeStatus.HasValue ?
                new ObjectParameter("entryCodeStatus", entryCodeStatus) :
                new ObjectParameter("entryCodeStatus", typeof(bool));
    
            var entryNameParameter = entryName != null ?
                new ObjectParameter("entryName", entryName) :
                new ObjectParameter("entryName", typeof(string));
    
            var entryDescriptionParameter = entryDescription != null ?
                new ObjectParameter("entryDescription", entryDescription) :
                new ObjectParameter("entryDescription", typeof(string));
    
            var userIDcreateParameter = userIDcreate.HasValue ?
                new ObjectParameter("userIDcreate", userIDcreate) :
                new ObjectParameter("userIDcreate", typeof(long));
    
            var dateCreateParameter = dateCreate.HasValue ?
                new ObjectParameter("dateCreate", dateCreate) :
                new ObjectParameter("dateCreate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Seguridad_P_GuardarPermiso", entryCodeModuleParameter, entryCodeStatusParameter, entryNameParameter, entryDescriptionParameter, userIDcreateParameter, dateCreateParameter, mENSAJE, rESPUESTA);
        }
    
        public virtual int Seguridad_P_EditarModulo(Nullable<long> entryCode, Nullable<bool> codeStatus, string name, string shortName, string description, Nullable<long> userIdUpdate, Nullable<System.DateTime> dateUpdate, ObjectParameter mENSAJE, ObjectParameter rESPUESTA)
        {
            var entryCodeParameter = entryCode.HasValue ?
                new ObjectParameter("entryCode", entryCode) :
                new ObjectParameter("entryCode", typeof(long));
    
            var codeStatusParameter = codeStatus.HasValue ?
                new ObjectParameter("CodeStatus", codeStatus) :
                new ObjectParameter("CodeStatus", typeof(bool));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var shortNameParameter = shortName != null ?
                new ObjectParameter("ShortName", shortName) :
                new ObjectParameter("ShortName", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var userIdUpdateParameter = userIdUpdate.HasValue ?
                new ObjectParameter("UserIdUpdate", userIdUpdate) :
                new ObjectParameter("UserIdUpdate", typeof(long));
    
            var dateUpdateParameter = dateUpdate.HasValue ?
                new ObjectParameter("DateUpdate", dateUpdate) :
                new ObjectParameter("DateUpdate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Seguridad_P_EditarModulo", entryCodeParameter, codeStatusParameter, nameParameter, shortNameParameter, descriptionParameter, userIdUpdateParameter, dateUpdateParameter, mENSAJE, rESPUESTA);
        }
    
        public virtual int Seguridad_P_EditarPermiso(Nullable<int> entryCode, Nullable<bool> entryCodeStatus, string entryName, string entryDescription, Nullable<int> userIDupdate, Nullable<System.DateTime> dateUpdate, ObjectParameter mENSAJE, ObjectParameter rESPUESTA)
        {
            var entryCodeParameter = entryCode.HasValue ?
                new ObjectParameter("entryCode", entryCode) :
                new ObjectParameter("entryCode", typeof(int));
    
            var entryCodeStatusParameter = entryCodeStatus.HasValue ?
                new ObjectParameter("entryCodeStatus", entryCodeStatus) :
                new ObjectParameter("entryCodeStatus", typeof(bool));
    
            var entryNameParameter = entryName != null ?
                new ObjectParameter("entryName", entryName) :
                new ObjectParameter("entryName", typeof(string));
    
            var entryDescriptionParameter = entryDescription != null ?
                new ObjectParameter("entryDescription", entryDescription) :
                new ObjectParameter("entryDescription", typeof(string));
    
            var userIDupdateParameter = userIDupdate.HasValue ?
                new ObjectParameter("userIDupdate", userIDupdate) :
                new ObjectParameter("userIDupdate", typeof(int));
    
            var dateUpdateParameter = dateUpdate.HasValue ?
                new ObjectParameter("dateUpdate", dateUpdate) :
                new ObjectParameter("dateUpdate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Seguridad_P_EditarPermiso", entryCodeParameter, entryCodeStatusParameter, entryNameParameter, entryDescriptionParameter, userIDupdateParameter, dateUpdateParameter, mENSAJE, rESPUESTA);
        }
    
        [DbFunction("LegasyEntities", "Seguridad_Fn_ModuloSeleccionado")]
        public virtual IQueryable<Seguridad_Fn_ModuloSeleccionado_Result> Seguridad_Fn_ModuloSeleccionado(Nullable<int> codEntry)
        {
            var codEntryParameter = codEntry.HasValue ?
                new ObjectParameter("codEntry", codEntry) :
                new ObjectParameter("codEntry", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Seguridad_Fn_ModuloSeleccionado_Result>("[LegasyEntities].[Seguridad_Fn_ModuloSeleccionado](@codEntry)", codEntryParameter);
        }
    
        [DbFunction("LegasyEntities", "Seguridad_Fn_PermisoSeleccionado")]
        public virtual IQueryable<Seguridad_Fn_PermisoSeleccionado_Result> Seguridad_Fn_PermisoSeleccionado(Nullable<int> idPermiso)
        {
            var idPermisoParameter = idPermiso.HasValue ?
                new ObjectParameter("IdPermiso", idPermiso) :
                new ObjectParameter("IdPermiso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Seguridad_Fn_PermisoSeleccionado_Result>("[LegasyEntities].[Seguridad_Fn_PermisoSeleccionado](@IdPermiso)", idPermisoParameter);
        }
    
        [DbFunction("LegasyEntities", "Seguridad_Fn_MostrarUsuarios")]
        public virtual IQueryable<Seguridad_Fn_MostrarUsuarios_Result> Seguridad_Fn_MostrarUsuarios()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Seguridad_Fn_MostrarUsuarios_Result>("[LegasyEntities].[Seguridad_Fn_MostrarUsuarios]()");
        }
    
        [DbFunction("LegasyEntities", "Seguridad_Fn_UsuarioSeleccionado")]
        public virtual IQueryable<Seguridad_Fn_UsuarioSeleccionado_Result> Seguridad_Fn_UsuarioSeleccionado(Nullable<int> entryCode)
        {
            var entryCodeParameter = entryCode.HasValue ?
                new ObjectParameter("entryCode", entryCode) :
                new ObjectParameter("entryCode", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Seguridad_Fn_UsuarioSeleccionado_Result>("[LegasyEntities].[Seguridad_Fn_UsuarioSeleccionado](@entryCode)", entryCodeParameter);
        }
    
        public virtual int Seguridad_P_GuardarUsuario(Nullable<bool> codeStatus, string displayName, string email, string userName, string password, Nullable<long> userIdCreate, Nullable<System.DateTime> dateCreate, ObjectParameter mENSAJE, ObjectParameter rESPUESTA)
        {
            var codeStatusParameter = codeStatus.HasValue ?
                new ObjectParameter("CodeStatus", codeStatus) :
                new ObjectParameter("CodeStatus", typeof(bool));
    
            var displayNameParameter = displayName != null ?
                new ObjectParameter("DisplayName", displayName) :
                new ObjectParameter("DisplayName", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var userIdCreateParameter = userIdCreate.HasValue ?
                new ObjectParameter("UserIdCreate", userIdCreate) :
                new ObjectParameter("UserIdCreate", typeof(long));
    
            var dateCreateParameter = dateCreate.HasValue ?
                new ObjectParameter("DateCreate", dateCreate) :
                new ObjectParameter("DateCreate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Seguridad_P_GuardarUsuario", codeStatusParameter, displayNameParameter, emailParameter, userNameParameter, passwordParameter, userIdCreateParameter, dateCreateParameter, mENSAJE, rESPUESTA);
        }
    
        public virtual int Seguridad_P_Usuario_RemoveAllModulos(Nullable<int> idUsuario)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Seguridad_P_Usuario_RemoveAllModulos", idUsuarioParameter);
        }
    
        public virtual int Seguridad_P_Usuario_SetModulo(Nullable<int> idUsuario, Nullable<int> idModulo, Nullable<int> usuarioRegistro)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            var idModuloParameter = idModulo.HasValue ?
                new ObjectParameter("IdModulo", idModulo) :
                new ObjectParameter("IdModulo", typeof(int));
    
            var usuarioRegistroParameter = usuarioRegistro.HasValue ?
                new ObjectParameter("UsuarioRegistro", usuarioRegistro) :
                new ObjectParameter("UsuarioRegistro", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Seguridad_P_Usuario_SetModulo", idUsuarioParameter, idModuloParameter, usuarioRegistroParameter);
        }
    
        public virtual int Seguridad_P_Usuario_RemoveAllPermisos(Nullable<int> idUsuario)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Seguridad_P_Usuario_RemoveAllPermisos", idUsuarioParameter);
        }
    
        public virtual int Seguridad_P_Usuario_SetPermisos(Nullable<int> idUsuario, Nullable<int> idPermiso, Nullable<int> usuarioRegistro)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            var idPermisoParameter = idPermiso.HasValue ?
                new ObjectParameter("IdPermiso", idPermiso) :
                new ObjectParameter("IdPermiso", typeof(int));
    
            var usuarioRegistroParameter = usuarioRegistro.HasValue ?
                new ObjectParameter("UsuarioRegistro", usuarioRegistro) :
                new ObjectParameter("UsuarioRegistro", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Seguridad_P_Usuario_SetPermisos", idUsuarioParameter, idPermisoParameter, usuarioRegistroParameter);
        }
    
        [DbFunction("LegasyEntities", "Seguridad_Fn_ValidaModulo")]
        public virtual IQueryable<Seguridad_Fn_ValidaModulo_Result> Seguridad_Fn_ValidaModulo(Nullable<long> idUsuario, Nullable<long> idModulo)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(long));
    
            var idModuloParameter = idModulo.HasValue ?
                new ObjectParameter("IdModulo", idModulo) :
                new ObjectParameter("IdModulo", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Seguridad_Fn_ValidaModulo_Result>("[LegasyEntities].[Seguridad_Fn_ValidaModulo](@IdUsuario, @IdModulo)", idUsuarioParameter, idModuloParameter);
        }
    
        [DbFunction("LegasyEntities", "Seguridad_Fn_ValidaPermiso")]
        public virtual IQueryable<Seguridad_Fn_ValidaPermiso_Result> Seguridad_Fn_ValidaPermiso(Nullable<long> idUsuario, Nullable<long> idModulo)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(long));
    
            var idModuloParameter = idModulo.HasValue ?
                new ObjectParameter("IdModulo", idModulo) :
                new ObjectParameter("IdModulo", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Seguridad_Fn_ValidaPermiso_Result>("[LegasyEntities].[Seguridad_Fn_ValidaPermiso](@IdUsuario, @IdModulo)", idUsuarioParameter, idModuloParameter);
        }
    
        [DbFunction("LegasyEntities", "Personaliza_Fn_ListaEmpresas")]
        public virtual IQueryable<Personaliza_Fn_ListaEmpresas_Result> Personaliza_Fn_ListaEmpresas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Personaliza_Fn_ListaEmpresas_Result>("[LegasyEntities].[Personaliza_Fn_ListaEmpresas]()");
        }
    
        public virtual int Personaliza_P_GuardarEmpresas(string nombre, string descripcion, string persona, string direccion, string identidad1, string identidad2, string identidad3, string telefono1, string telefono2, string telefono3, string correo, string comentarios, Nullable<long> usuarioRegistro, Nullable<System.DateTime> fechaRegistro, ObjectParameter mENSAJE, ObjectParameter rESPUESTA)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var personaParameter = persona != null ?
                new ObjectParameter("Persona", persona) :
                new ObjectParameter("Persona", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("Direccion", direccion) :
                new ObjectParameter("Direccion", typeof(string));
    
            var identidad1Parameter = identidad1 != null ?
                new ObjectParameter("Identidad1", identidad1) :
                new ObjectParameter("Identidad1", typeof(string));
    
            var identidad2Parameter = identidad2 != null ?
                new ObjectParameter("Identidad2", identidad2) :
                new ObjectParameter("Identidad2", typeof(string));
    
            var identidad3Parameter = identidad3 != null ?
                new ObjectParameter("Identidad3", identidad3) :
                new ObjectParameter("Identidad3", typeof(string));
    
            var telefono1Parameter = telefono1 != null ?
                new ObjectParameter("Telefono1", telefono1) :
                new ObjectParameter("Telefono1", typeof(string));
    
            var telefono2Parameter = telefono2 != null ?
                new ObjectParameter("Telefono2", telefono2) :
                new ObjectParameter("Telefono2", typeof(string));
    
            var telefono3Parameter = telefono3 != null ?
                new ObjectParameter("Telefono3", telefono3) :
                new ObjectParameter("Telefono3", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var comentariosParameter = comentarios != null ?
                new ObjectParameter("Comentarios", comentarios) :
                new ObjectParameter("Comentarios", typeof(string));
    
            var usuarioRegistroParameter = usuarioRegistro.HasValue ?
                new ObjectParameter("UsuarioRegistro", usuarioRegistro) :
                new ObjectParameter("UsuarioRegistro", typeof(long));
    
            var fechaRegistroParameter = fechaRegistro.HasValue ?
                new ObjectParameter("FechaRegistro", fechaRegistro) :
                new ObjectParameter("FechaRegistro", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Personaliza_P_GuardarEmpresas", nombreParameter, descripcionParameter, personaParameter, direccionParameter, identidad1Parameter, identidad2Parameter, identidad3Parameter, telefono1Parameter, telefono2Parameter, telefono3Parameter, correoParameter, comentariosParameter, usuarioRegistroParameter, fechaRegistroParameter, mENSAJE, rESPUESTA);
        }
    
        [DbFunction("LegasyEntities", "Personaliza_Fn_EmpresaSeleccionada")]
        public virtual IQueryable<Personaliza_Fn_EmpresaSeleccionada_Result> Personaliza_Fn_EmpresaSeleccionada(Nullable<long> idEmpresa)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("IdEmpresa", idEmpresa) :
                new ObjectParameter("IdEmpresa", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Personaliza_Fn_EmpresaSeleccionada_Result>("[LegasyEntities].[Personaliza_Fn_EmpresaSeleccionada](@IdEmpresa)", idEmpresaParameter);
        }
    
        public virtual int Personaliza_P_EditarEmpresas(Nullable<long> idEmpresa, string nombre, string descripcion, string persona, string direccion, string identidad1, string identidad2, string identidad3, string telefono1, string telefono2, string telefono3, string correo, string comentarios, Nullable<long> usuarioEdicion, Nullable<System.DateTime> fechaReEdicion, ObjectParameter mENSAJE, ObjectParameter rESPUESTA)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("IdEmpresa", idEmpresa) :
                new ObjectParameter("IdEmpresa", typeof(long));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var personaParameter = persona != null ?
                new ObjectParameter("Persona", persona) :
                new ObjectParameter("Persona", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("Direccion", direccion) :
                new ObjectParameter("Direccion", typeof(string));
    
            var identidad1Parameter = identidad1 != null ?
                new ObjectParameter("Identidad1", identidad1) :
                new ObjectParameter("Identidad1", typeof(string));
    
            var identidad2Parameter = identidad2 != null ?
                new ObjectParameter("Identidad2", identidad2) :
                new ObjectParameter("Identidad2", typeof(string));
    
            var identidad3Parameter = identidad3 != null ?
                new ObjectParameter("Identidad3", identidad3) :
                new ObjectParameter("Identidad3", typeof(string));
    
            var telefono1Parameter = telefono1 != null ?
                new ObjectParameter("Telefono1", telefono1) :
                new ObjectParameter("Telefono1", typeof(string));
    
            var telefono2Parameter = telefono2 != null ?
                new ObjectParameter("Telefono2", telefono2) :
                new ObjectParameter("Telefono2", typeof(string));
    
            var telefono3Parameter = telefono3 != null ?
                new ObjectParameter("Telefono3", telefono3) :
                new ObjectParameter("Telefono3", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var comentariosParameter = comentarios != null ?
                new ObjectParameter("Comentarios", comentarios) :
                new ObjectParameter("Comentarios", typeof(string));
    
            var usuarioEdicionParameter = usuarioEdicion.HasValue ?
                new ObjectParameter("UsuarioEdicion", usuarioEdicion) :
                new ObjectParameter("UsuarioEdicion", typeof(long));
    
            var fechaReEdicionParameter = fechaReEdicion.HasValue ?
                new ObjectParameter("FechaReEdicion", fechaReEdicion) :
                new ObjectParameter("FechaReEdicion", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Personaliza_P_EditarEmpresas", idEmpresaParameter, nombreParameter, descripcionParameter, personaParameter, direccionParameter, identidad1Parameter, identidad2Parameter, identidad3Parameter, telefono1Parameter, telefono2Parameter, telefono3Parameter, correoParameter, comentariosParameter, usuarioEdicionParameter, fechaReEdicionParameter, mENSAJE, rESPUESTA);
        }
    
        public virtual int Personaliza_P_GuardarSucursal(Nullable<long> idEmpresa, string nombre, string descripcion, string persona, string direccion, string identidad1, string identidad2, string identidad3, string telefono1, string telefono2, string telefono3, string correo, string comentarios, Nullable<long> usuarioRegistro, Nullable<System.DateTime> fechaRegistro, ObjectParameter mENSAJE, ObjectParameter rESPUESTA)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("IdEmpresa", idEmpresa) :
                new ObjectParameter("IdEmpresa", typeof(long));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var personaParameter = persona != null ?
                new ObjectParameter("Persona", persona) :
                new ObjectParameter("Persona", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("Direccion", direccion) :
                new ObjectParameter("Direccion", typeof(string));
    
            var identidad1Parameter = identidad1 != null ?
                new ObjectParameter("Identidad1", identidad1) :
                new ObjectParameter("Identidad1", typeof(string));
    
            var identidad2Parameter = identidad2 != null ?
                new ObjectParameter("Identidad2", identidad2) :
                new ObjectParameter("Identidad2", typeof(string));
    
            var identidad3Parameter = identidad3 != null ?
                new ObjectParameter("Identidad3", identidad3) :
                new ObjectParameter("Identidad3", typeof(string));
    
            var telefono1Parameter = telefono1 != null ?
                new ObjectParameter("Telefono1", telefono1) :
                new ObjectParameter("Telefono1", typeof(string));
    
            var telefono2Parameter = telefono2 != null ?
                new ObjectParameter("Telefono2", telefono2) :
                new ObjectParameter("Telefono2", typeof(string));
    
            var telefono3Parameter = telefono3 != null ?
                new ObjectParameter("Telefono3", telefono3) :
                new ObjectParameter("Telefono3", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var comentariosParameter = comentarios != null ?
                new ObjectParameter("Comentarios", comentarios) :
                new ObjectParameter("Comentarios", typeof(string));
    
            var usuarioRegistroParameter = usuarioRegistro.HasValue ?
                new ObjectParameter("UsuarioRegistro", usuarioRegistro) :
                new ObjectParameter("UsuarioRegistro", typeof(long));
    
            var fechaRegistroParameter = fechaRegistro.HasValue ?
                new ObjectParameter("FechaRegistro", fechaRegistro) :
                new ObjectParameter("FechaRegistro", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Personaliza_P_GuardarSucursal", idEmpresaParameter, nombreParameter, descripcionParameter, personaParameter, direccionParameter, identidad1Parameter, identidad2Parameter, identidad3Parameter, telefono1Parameter, telefono2Parameter, telefono3Parameter, correoParameter, comentariosParameter, usuarioRegistroParameter, fechaRegistroParameter, mENSAJE, rESPUESTA);
        }
    
        [DbFunction("LegasyEntities", "Personaliza_Fn_ListaSucursales")]
        public virtual IQueryable<Personaliza_Fn_ListaSucursales_Result> Personaliza_Fn_ListaSucursales()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Personaliza_Fn_ListaSucursales_Result>("[LegasyEntities].[Personaliza_Fn_ListaSucursales]()");
        }
    
        public virtual int SP_ValidaSesion(Nullable<int> idSesion, string token, string hostClient, ObjectParameter respuesta, ObjectParameter usuario)
        {
            var idSesionParameter = idSesion.HasValue ?
                new ObjectParameter("IdSesion", idSesion) :
                new ObjectParameter("IdSesion", typeof(int));
    
            var tokenParameter = token != null ?
                new ObjectParameter("Token", token) :
                new ObjectParameter("Token", typeof(string));
    
            var hostClientParameter = hostClient != null ?
                new ObjectParameter("HostClient", hostClient) :
                new ObjectParameter("HostClient", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ValidaSesion", idSesionParameter, tokenParameter, hostClientParameter, respuesta, usuario);
        }
    
        [DbFunction("LegasyEntities", "Session_Fn_EvaluaSesion")]
        public virtual IQueryable<Session_Fn_EvaluaSesion_Result> Session_Fn_EvaluaSesion(Nullable<int> idSesion, string token)
        {
            var idSesionParameter = idSesion.HasValue ?
                new ObjectParameter("IdSesion", idSesion) :
                new ObjectParameter("IdSesion", typeof(int));
    
            var tokenParameter = token != null ?
                new ObjectParameter("Token", token) :
                new ObjectParameter("Token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Session_Fn_EvaluaSesion_Result>("[LegasyEntities].[Session_Fn_EvaluaSesion](@IdSesion, @Token)", idSesionParameter, tokenParameter);
        }
    }
}
