//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LEGASY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subsidiaries
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subsidiaries()
        {
            this.Partners = new HashSet<Partners>();
        }
    
        public long entryCode { get; set; }
        public long entryCodeCompany { get; set; }
        public string entryName { get; set; }
        public string entryDescription { get; set; }
        public string entryPerson { get; set; }
        public string entryAddress { get; set; }
        public string entryID1 { get; set; }
        public string entryID2 { get; set; }
        public string entryID3 { get; set; }
        public string entryPhone1 { get; set; }
        public string entryPhone2 { get; set; }
        public string entryPhone3 { get; set; }
        public string entryEmail { get; set; }
        public string entryComments { get; set; }
        public Nullable<long> userIDcreate { get; set; }
        public Nullable<long> userIDupdate { get; set; }
        public Nullable<System.DateTime> dateCreate { get; set; }
        public Nullable<System.DateTime> dateUpdate { get; set; }
    
        public virtual Companies Companies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Partners> Partners { get; set; }
    }
}
